### ISSUE TITLE
Prefer env vars over actual URL

### ISSUE THREAD

**Issue by jirevwe** [random-guys/lux#17]
https://github.com/random-guys/lux/blob/9f9e2fdecf014acdce3e988662d76c55fcab63ba/__tests__/lux.spec.ts#L5

This repo is public, it won't make sense to use the actual URL.

**Comment by noxecane** [comment]
That skipped me...could make a PR that uses [this](http://www.dneonline.com/calculator.asmx?WSDL) instead and uses an `$ENV`
